% Array of Objects not supported for codegen, create struct with similar
% format - track prototype structure

% Use adsbCategory enumeration (matches what Exercise3 uses)
% Initialize with No_Category_Information (default)
adsbCat = adsbCategory.No_Category_Information;  % adsbCategory enumeration type

% ObjectAttributes prototype: callsign fixed 8-char; category adsbCategory
protoObjAttrs = struct( ...
    'Callsign', repmat(' ',1,8), ...
    'Category', adsbCat);

% Create two prototypes: one for ADSB tracks (History), one for Radar tracks (Integrated)
% The array will contain a mix of both types

protoTrackADSB = struct( ...
    'TrackID',          uint32(0), ...
    'BranchID',         uint32(0), ...
    'SourceIndex',      uint32(0), ...
    'UpdateTime',       double(0), ...
    'Age',              uint32(0), ...
    'State',            zeros(6,1,'double'), ...
    'StateCovariance',  eye(6,'double'), ...
    'StateParameters',  struct(), ...
    'ObjectClassID',    double(0), ...
    'ObjectClassProbabilities',  coder.typeof(double(0), [1 10], [0 1]), ...
    'TrackLogic',       'History', ...  % 7 chars - ADSB uses History
    'TrackLogicState',  coder.typeof(double(0), [1 10], [0 1]), ...
    'IsConfirmed',      false, ...
    'IsCoasted',        false, ...
    'IsSelfReported',   false, ...
    'ObjectAttributes', protoObjAttrs);

protoTrackRadar = struct( ...
    'TrackID',          uint32(0), ...
    'BranchID',         uint32(0), ...
    'SourceIndex',      uint32(0), ...
    'UpdateTime',       double(0), ...
    'Age',              uint32(0), ...
    'State',            zeros(6,1,'double'), ...
    'StateCovariance',  eye(6,'double'), ...
    'StateParameters',  struct(), ...
    'ObjectClassID',    double(0), ...
    'ObjectClassProbabilities',  coder.typeof(double(0), [1 10], [0 1]), ...
    'TrackLogic',       'Integrated', ...  % 10 chars - Radar uses Integrated
    'TrackLogicState',  coder.typeof(double(0), [1 10], [0 1]), ...
    'IsConfirmed',      false, ...
    'IsCoasted',        false, ...
    'IsSelfReported',   false, ...
    'ObjectAttributes', protoObjAttrs);

% Use the LONGEST TrackLogic ('Integrated' = 10 chars) as the prototype
% This allows both 'History' (7 chars, padded) and 'Integrated' (10 chars)
% to coexist in the same array
trackInput = coder.typeof(protoTrackRadar, [200 1], [true false]);
time = 0;

% Generate MEX of ToT tracker
codegen -report fusionAlgorithm -args {trackInput, time}