function scenario = helperCreateScenario(tuningData, mapOrigin,scenarioDuration)
%scenarioDuration = 200; % s (reduced from 200 for workshop speed)
scenario = trackingScenario(UpdateRate=1,StopTime=scenarioDuration,IsEarthCentered=true);
radarTower = platform(scenario, Position=mapOrigin);

beamwidthAz = 360;
fov = [beamwidthAz; 15];
updaterate = 1;
activeRadar = fusionRadarSensor(1,"No Scanning", ...
    UpdateRate=updaterate, ...
    FieldOfView=fov, ...
    AzimuthResolution=1.4, ...
    ReferenceRange=111e3, ...
    ReferenceRCS=0, ...
    RangeResolution=135, ...
    HasElevation=true, ...
    HasNoise=true, ...
    HasFalseAlarms=true, ...
    FalseAlarmRate=1e-7,...
    HasRangeRate=true, ...
    RangeRateLimits=[-600 600], ...
    MountingLocation=[0 0 -15], ...
    MountingAngles=[0 0 0], ...
    HasINS=true, ...
    DetectionCoordinates="Sensor spherical");

radarTower.Sensors = activeRadar;
elFov = fov(2);
activeRadar.FieldOfView(2) = elFov+1e-3;

applehillPos = [42.300498, -71.349157 0];
ADSBTower = platform(scenario, Position=applehillPos); %#ok<NASGU>

for i = 1:numel(tuningData)
    Pos = tuningData{i}.Position;
    time = seconds(tuningData{i}.Time);
    validIdx = time <= scenarioDuration;
    truncatedTime = time(validIdx);
    truncatedPos = Pos(validIdx, :);
    traj = geoTrajectory(truncatedPos,truncatedTime);
    platform(scenario,Trajectory=traj);
end
end