function transponderStruct = helperCreateTX(numPlats, gps)
    transponderStruct(numPlats) = struct();
    for i = 1:numPlats
        tailNumber = sprintf('MW%d', 2019 + i);
        transponderStruct(i).adsbTx = adsbTransponder( ...
            tailNumber, ...
            'UpdateRate', 1, ...
            'GPS', gps, ...
            'Category', adsbCategory.Large);
    end
end