function tracksObj = helperConvertToObjectTrack(tracksStruct)
    tracksObj = repmat(objectTrack, numel(tracksStruct), 1);
    for i = 1:numel(tracksStruct)
        trackLogic = strtrim(tracksStruct(i).TrackLogic);
        tracksObj(i) = objectTrack( ...
            'TrackID', tracksStruct(i).TrackID, ...
            'BranchID', tracksStruct(i).BranchID, ...
            'SourceIndex', tracksStruct(i).SourceIndex, ...
            'UpdateTime', tracksStruct(i).UpdateTime, ...
            'Age', tracksStruct(i).Age, ...
            'State', tracksStruct(i).State, ...
            'StateCovariance', tracksStruct(i).StateCovariance, ...
            'StateParameters', tracksStruct(i).StateParameters, ...
            'ObjectClassID', tracksStruct(i).ObjectClassID, ...
            'ObjectClassProbabilities', tracksStruct(i).ObjectClassProbabilities, ...
            'TrackLogic', trackLogic, ...
            'TrackLogicState', tracksStruct(i).TrackLogicState, ...
            'IsConfirmed', tracksStruct(i).IsConfirmed, ...
            'IsCoasted', tracksStruct(i).IsCoasted, ...
            'IsSelfReported', tracksStruct(i).IsSelfReported, ...
            'ObjectAttributes', tracksStruct(i).ObjectAttributes ...
        );
    end
end