function tr1 = helperSyncTrack(tr1,tr2)
props = {...
    'TrackID', ...
    'BranchID', ...
    'SourceIndex', ...
    'UpdateTime', ...
    'Age', ...
    'StateParameters', ...
    'ObjectClassID', ...
    'IsConfirmed', ...
    'IsCoasted', ...
    'IsSelfReported', ...
    'ObjectAttributes'};
for i = 1:numel(props)
    tr1.(props{i}) = tr2.(props{i});
end
end