function transponderStruct = helperCreateTX(scenario, gps)
    numPlats = numel(scenario.Platforms)-2; % Two platforms in scene are the sensor towers
    transponderStruct(numPlats) = struct();
    for i = 1:numPlats
        tailNumber = sprintf('MW%d', 2019 + i);
        transponderStruct(i).adsbTx = adsbTransponder( ...
            tailNumber, ...
            'UpdateRate', 1, ...
            'GPS', gps, ...
            'Category', adsbCategory.Large);
    end
end